name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Build Android release APK when create new tag
       uses: kyze8439690/action-release-releaseapk@1.0.0
            
